///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SimpleRanorexUiTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("e885ba9a-46b0-4a78-9894-da2ed9399938", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SimpleRanorexUiTestRepository repository.
        /// </summary>
        public static SimpleRanorexUiTestRepository repo = SimpleRanorexUiTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://nbc.com' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://nbc.com", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NBCTVNetworkShowsEpisodesSchedu.Shows' at 18;1.", repo.NBCTVNetworkShowsEpisodesSchedu.ShowsInfo, new RecordItemIndex(1));
            repo.NBCTVNetworkShowsEpisodesSchedu.Shows.Click("18;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NBCTVNetworkShowsEpisodesSchedu.Shop' at 20;4.", repo.NBCTVNetworkShowsEpisodesSchedu.ShopInfo, new RecordItemIndex(2));
            repo.NBCTVNetworkShowsEpisodesSchedu.Shop.Click("20;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NBCOfficialStoreTShirtsGiftsMu.HttpsWwwNbcstoreComSkinFrontendS' at 108;19.", repo.NBCOfficialStoreTShirtsGiftsMu.HttpsWwwNbcstoreComSkinFrontendSInfo, new RecordItemIndex(3));
            repo.NBCOfficialStoreTShirtsGiftsMu.HttpsWwwNbcstoreComSkinFrontendS.MoveTo("108;19");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NBCOfficialStoreTShirtsGiftsMu.HttpsWwwNbcstoreComSkinFrontendS' at 116;6.", repo.NBCOfficialStoreTShirtsGiftsMu.HttpsWwwNbcstoreComSkinFrontendSInfo, new RecordItemIndex(4));
            repo.NBCOfficialStoreTShirtsGiftsMu.HttpsWwwNbcstoreComSkinFrontendS.MoveTo("116;6");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NBCOfficialStoreTShirtsGiftsMu1.Pane' at 356;10.", repo.NBCOfficialStoreTShirtsGiftsMu1.PaneInfo, new RecordItemIndex(5));
            repo.NBCOfficialStoreTShirtsGiftsMu1.Pane.MoveTo("356;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NBCOfficialStoreTShirtsGiftsMu1.Pane' at 364;2.", repo.NBCOfficialStoreTShirtsGiftsMu1.PaneInfo, new RecordItemIndex(6));
            repo.NBCOfficialStoreTShirtsGiftsMu1.Pane.MoveTo("364;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NBCOfficialStoreTShirtsGiftsMu1.Pane1' at 512;15.", repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1Info, new RecordItemIndex(7));
            repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1.MoveTo("512;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMu' at 72;6.", repo.NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMuInfo, new RecordItemIndex(8));
            repo.NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMu.MoveTo("72;6");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMu' at 80;-2.", repo.NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMuInfo, new RecordItemIndex(9));
            repo.NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMu.MoveTo("80;-2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NBCOfficialStoreTShirtsGiftsMu1.Pane1' at 451;3.", repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1Info, new RecordItemIndex(10));
            repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1.MoveTo("451;3");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NBCOfficialStoreTShirtsGiftsMu1.Pane1' at 448;11.", repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1Info, new RecordItemIndex(11));
            repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1.MoveTo("448;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NBCOfficialStoreTShirtsGiftsMu1.Pane1' at 608;13.", repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1Info, new RecordItemIndex(12));
            repo.NBCOfficialStoreTShirtsGiftsMu1.Pane1.MoveTo("608;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMu' at 75;8.", repo.NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMuInfo, new RecordItemIndex(13));
            repo.NBCOfficialStoreTShirtsGiftsMu1.NBCOfficialStoreTShirtsGiftsMu.Click("75;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -5536 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-5536);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NBCOfficialStoreTShirtsGiftsMu.ShopByBravo' at 41;3.", repo.NBCOfficialStoreTShirtsGiftsMu.ShopByBravoInfo, new RecordItemIndex(15));
            repo.NBCOfficialStoreTShirtsGiftsMu.ShopByBravo.Click("41;3");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
