///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SimpleRanorexUiTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SimpleRanorexUiTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("7731005b-d34c-400b-9b2e-6ec52297551d")]
    public partial class SimpleRanorexUiTestRepository : RepoGenBaseFolder
    {
        static SimpleRanorexUiTestRepository instance = new SimpleRanorexUiTestRepository();
        SimpleRanorexUiTestRepositoryFolders.NBCTVNetworkShowsEpisodesScheduAppFolder _nbctvnetworkshowsepisodesschedu;
        SimpleRanorexUiTestRepositoryFolders.NBCOfficialStoreTShirtsGiftsMuAppFolder _nbcofficialstoretshirtsgiftsmu;
        SimpleRanorexUiTestRepositoryFolders.NBCOfficialStoreTShirtsGiftsMu1AppFolder _nbcofficialstoretshirtsgiftsmu1;

        /// <summary>
        /// Gets the singleton class instance representing the SimpleRanorexUiTestRepository element repository.
        /// </summary>
        [RepositoryFolder("7731005b-d34c-400b-9b2e-6ec52297551d")]
        public static SimpleRanorexUiTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SimpleRanorexUiTestRepository() 
            : base("SimpleRanorexUiTestRepository", "/", null, 0, false, "7731005b-d34c-400b-9b2e-6ec52297551d", ".\\RepositoryImages\\SimpleRanorexUiTestRepository7731005b.rximgres")
        {
            _nbctvnetworkshowsepisodesschedu = new SimpleRanorexUiTestRepositoryFolders.NBCTVNetworkShowsEpisodesScheduAppFolder(this);
            _nbcofficialstoretshirtsgiftsmu = new SimpleRanorexUiTestRepositoryFolders.NBCOfficialStoreTShirtsGiftsMuAppFolder(this);
            _nbcofficialstoretshirtsgiftsmu1 = new SimpleRanorexUiTestRepositoryFolders.NBCOfficialStoreTShirtsGiftsMu1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7731005b-d34c-400b-9b2e-6ec52297551d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NBCTVNetworkShowsEpisodesSchedu folder.
        /// </summary>
        [RepositoryFolder("98c569c6-79cd-4ad0-995c-43154ef81d03")]
        public virtual SimpleRanorexUiTestRepositoryFolders.NBCTVNetworkShowsEpisodesScheduAppFolder NBCTVNetworkShowsEpisodesSchedu
        {
            get { return _nbctvnetworkshowsepisodesschedu; }
        }

        /// <summary>
        /// The NBCOfficialStoreTShirtsGiftsMu folder.
        /// </summary>
        [RepositoryFolder("1838991b-d118-4bb0-aec9-5230bdb9e34c")]
        public virtual SimpleRanorexUiTestRepositoryFolders.NBCOfficialStoreTShirtsGiftsMuAppFolder NBCOfficialStoreTShirtsGiftsMu
        {
            get { return _nbcofficialstoretshirtsgiftsmu; }
        }

        /// <summary>
        /// The NBCOfficialStoreTShirtsGiftsMu1 folder.
        /// </summary>
        [RepositoryFolder("da82cec8-766c-46cb-bf94-cc183458ebe0")]
        public virtual SimpleRanorexUiTestRepositoryFolders.NBCOfficialStoreTShirtsGiftsMu1AppFolder NBCOfficialStoreTShirtsGiftsMu1
        {
            get { return _nbcofficialstoretshirtsgiftsmu1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class SimpleRanorexUiTestRepositoryFolders
    {
        /// <summary>
        /// The NBCTVNetworkShowsEpisodesScheduAppFolder folder.
        /// </summary>
        [RepositoryFolder("98c569c6-79cd-4ad0-995c-43154ef81d03")]
        public partial class NBCTVNetworkShowsEpisodesScheduAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _showsInfo;
            RepoItemInfo _shopInfo;

            /// <summary>
            /// Creates a new NBCTVNetworkShowsEpisodesSchedu  folder.
            /// </summary>
            public NBCTVNetworkShowsEpisodesScheduAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NBCTVNetworkShowsEpisodesSchedu", "/dom[@caption~'^NBC\\ TV\\ Network\\ -\\ Shows,\\ E']", parentFolder, 30000, null, false, "98c569c6-79cd-4ad0-995c-43154ef81d03", "")
            {
                _showsInfo = new RepoItemInfo(this, "Shows", ".//div[#'app']/?/?/header//nav/?/?/ul/li[2]/?/?/span[@innertext='Shows']", 30000, null, "a58a650a-63eb-4764-8124-2cf9246f5850");
                _shopInfo = new RepoItemInfo(this, "Shop", ".//div[#'app']/?/?/header//nav/?/?/ul/li[6]/?/?/span[@innertext='Shop']", 30000, null, "b2fadd1b-06c3-49fe-b957-51e836b88f9d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("98c569c6-79cd-4ad0-995c-43154ef81d03")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("98c569c6-79cd-4ad0-995c-43154ef81d03")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Shows item.
            /// </summary>
            [RepositoryItem("a58a650a-63eb-4764-8124-2cf9246f5850")]
            public virtual Ranorex.SpanTag Shows
            {
                get
                {
                    return _showsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Shows item info.
            /// </summary>
            [RepositoryItemInfo("a58a650a-63eb-4764-8124-2cf9246f5850")]
            public virtual RepoItemInfo ShowsInfo
            {
                get
                {
                    return _showsInfo;
                }
            }

            /// <summary>
            /// The Shop item.
            /// </summary>
            [RepositoryItem("b2fadd1b-06c3-49fe-b957-51e836b88f9d")]
            public virtual Ranorex.SpanTag Shop
            {
                get
                {
                    return _shopInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Shop item info.
            /// </summary>
            [RepositoryItemInfo("b2fadd1b-06c3-49fe-b957-51e836b88f9d")]
            public virtual RepoItemInfo ShopInfo
            {
                get
                {
                    return _shopInfo;
                }
            }
        }

        /// <summary>
        /// The NBCOfficialStoreTShirtsGiftsMuAppFolder folder.
        /// </summary>
        [RepositoryFolder("1838991b-d118-4bb0-aec9-5230bdb9e34c")]
        public partial class NBCOfficialStoreTShirtsGiftsMuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpswwwnbcstorecomskinfrontendsInfo;
            RepoItemInfo _shopbybravoInfo;

            /// <summary>
            /// Creates a new NBCOfficialStoreTShirtsGiftsMu  folder.
            /// </summary>
            public NBCOfficialStoreTShirtsGiftsMuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NBCOfficialStoreTShirtsGiftsMu", "/dom[@domain='www.nbcstore.com']", parentFolder, 30000, null, false, "1838991b-d118-4bb0-aec9-5230bdb9e34c", "")
            {
                _httpswwwnbcstorecomskinfrontendsInfo = new RepoItemInfo(this, "HttpsWwwNbcstoreComSkinFrontendS", ".//header[#'header']/?/?/a[@href='https://www.nbcstore.com/']/img[1]", 30000, null, "ee531e62-2604-493d-95d1-5d7c004da6af");
                _shopbybravoInfo = new RepoItemInfo(this, "ShopByBravo", "body/div[3]/div/div[7]/div[2]/ul/li[5]/ul/?/?/a[@innertext='Shop By Bravo']", 30000, null, "122e2aa2-49fc-4f66-9596-8c4af1e0d36c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1838991b-d118-4bb0-aec9-5230bdb9e34c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1838991b-d118-4bb0-aec9-5230bdb9e34c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwNbcstoreComSkinFrontendS item.
            /// </summary>
            [RepositoryItem("ee531e62-2604-493d-95d1-5d7c004da6af")]
            public virtual Ranorex.ImgTag HttpsWwwNbcstoreComSkinFrontendS
            {
                get
                {
                    return _httpswwwnbcstorecomskinfrontendsInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwNbcstoreComSkinFrontendS item info.
            /// </summary>
            [RepositoryItemInfo("ee531e62-2604-493d-95d1-5d7c004da6af")]
            public virtual RepoItemInfo HttpsWwwNbcstoreComSkinFrontendSInfo
            {
                get
                {
                    return _httpswwwnbcstorecomskinfrontendsInfo;
                }
            }

            /// <summary>
            /// The ShopByBravo item.
            /// </summary>
            [RepositoryItem("122e2aa2-49fc-4f66-9596-8c4af1e0d36c")]
            public virtual Ranorex.ATag ShopByBravo
            {
                get
                {
                    return _shopbybravoInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ShopByBravo item info.
            /// </summary>
            [RepositoryItemInfo("122e2aa2-49fc-4f66-9596-8c4af1e0d36c")]
            public virtual RepoItemInfo ShopByBravoInfo
            {
                get
                {
                    return _shopbybravoInfo;
                }
            }
        }

        /// <summary>
        /// The NBCOfficialStoreTShirtsGiftsMu1AppFolder folder.
        /// </summary>
        [RepositoryFolder("da82cec8-766c-46cb-bf94-cc183458ebe0")]
        public partial class NBCOfficialStoreTShirtsGiftsMu1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _pane1Info;
            RepoItemInfo _nbcofficialstoretshirtsgiftsmuInfo;

            /// <summary>
            /// Creates a new NBCOfficialStoreTShirtsGiftsMu1  folder.
            /// </summary>
            public NBCOfficialStoreTShirtsGiftsMu1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("NBCOfficialStoreTShirtsGiftsMu1", "/form[@title~'^NBC\\ Official\\ Store\\ \\|\\ T-Sh']", parentFolder, 30000, null, true, "da82cec8-766c-46cb-bf94-cc183458ebe0", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename~'^NBC\\ Official\\ Store\\ \\|\\ T-Sh']/container/container[1]", 30000, null, "a00f342c-78b2-4adb-b625-593f7a8f20c4");
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename~'^reselbob/SimpleRanorexUiT']/container/container[1]", 30000, null, "63cb7130-f25f-4f64-b08a-effa67953f56");
                _nbcofficialstoretshirtsgiftsmuInfo = new RepoItemInfo(this, "NBCOfficialStoreTShirtsGiftsMu", "container[@accessiblename~'^reselbob/SimpleRanorexUiT']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^NBC\\ Official\\ Store\\ \\|\\ T-Sh']/text[@accessiblename~'^NBC\\ Official\\ Store\\ \\|\\ T-Sh']", 30000, null, "e16644fd-bc6b-4dbe-98f3-fa09d765b3e7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da82cec8-766c-46cb-bf94-cc183458ebe0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da82cec8-766c-46cb-bf94-cc183458ebe0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("a00f342c-78b2-4adb-b625-593f7a8f20c4")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("a00f342c-78b2-4adb-b625-593f7a8f20c4")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("63cb7130-f25f-4f64-b08a-effa67953f56")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("63cb7130-f25f-4f64-b08a-effa67953f56")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }

            /// <summary>
            /// The NBCOfficialStoreTShirtsGiftsMu item.
            /// </summary>
            [RepositoryItem("e16644fd-bc6b-4dbe-98f3-fa09d765b3e7")]
            public virtual Ranorex.Text NBCOfficialStoreTShirtsGiftsMu
            {
                get
                {
                    return _nbcofficialstoretshirtsgiftsmuInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NBCOfficialStoreTShirtsGiftsMu item info.
            /// </summary>
            [RepositoryItemInfo("e16644fd-bc6b-4dbe-98f3-fa09d765b3e7")]
            public virtual RepoItemInfo NBCOfficialStoreTShirtsGiftsMuInfo
            {
                get
                {
                    return _nbcofficialstoretshirtsgiftsmuInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}